name: Update the repo
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install tools
        run: |
          sudo apt install apt-utils bzip2 gzip

      - uses: actions/checkout@v3
      - run: |
          ./pack.sh
          git config user.name  "action-user"
          git config user.email "action@github.com"
          git add .
          git commit -m "Updated the repo"
          git push
